/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteTwoRouteImport } from './routes/routeTwo'
import { Route as IndexRouteImport } from './routes/index'

const RouteTwoRoute = RouteTwoRouteImport.update({
  id: '/routeTwo',
  path: '/routeTwo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routeTwo': typeof RouteTwoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/routeTwo': typeof RouteTwoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/routeTwo': typeof RouteTwoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/routeTwo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/routeTwo'
  id: '__root__' | '/' | '/routeTwo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteTwoRoute: typeof RouteTwoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routeTwo': {
      id: '/routeTwo'
      path: '/routeTwo'
      fullPath: '/routeTwo'
      preLoaderRoute: typeof RouteTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteTwoRoute: RouteTwoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
