/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddAppRouteImport } from './routes/add-app'
import { Route as IndexRouteImport } from './routes/index'

const AddAppRoute = AddAppRouteImport.update({
  id: '/add-app',
  path: '/add-app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-app': typeof AddAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-app': typeof AddAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-app': typeof AddAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-app'
  id: '__root__' | '/' | '/add-app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddAppRoute: typeof AddAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-app': {
      id: '/add-app'
      path: '/add-app'
      fullPath: '/add-app'
      preLoaderRoute: typeof AddAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddAppRoute: AddAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
